package org.apache.storm.topology;

public enum BoltEnum {
    RICH_BOLT,
    BASIC_BOLT,
    WINDOWED_BOLT,
    UNSERIALIZABLE_RICH_BOLT,
    UNSERIALIZABLE_BASIC_BOLT,
    UNSERIALIZABLE_WINDOWED_BOLT,
    NULL_BOLT,
    STATEFUL_BOLT,
    STATEFUL_WINDOWED_BOLT,
    UNSERIALIZABLE_STATEFUL_BOLT,
    UNSERIALIZABLE_STATEFUL_WINDOWED_BOLT,
    NO_STATEFUL_BOLT,
}
